### ISSUE TITLE
The package assumes the message Body is a TransportMessage making it impossible to integrate with non-NServiceBus endpoints

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AwsLambda.Sqs#146]
When the NServiceBus Lambda package processes a message, it assumes that incoming messages are sent by NServiceBus: https://github.com/Particular/NServiceBus.AwsLambda.Sqs/blob/271034ea1ac5ec4924ed4e4cfe363b9279e24aa5/src/NServiceBus.AwsLambda.SQS/AwsLambdaEndpoint.cs#L215-L239 By blindly deserializing the incoming message to a `TransportMessage` instance https://github.com/Particular/NServiceBus.AwsLambda.Sqs/blob/271034ea1ac5ec4924ed4e4cfe363b9279e24aa5/src/NServiceBus.AwsLambda.SQS/AwsLambdaEndpoint.cs#L226. If deserialization fails, it's assumed the message is a poison message.

On the other hand, the [underlying transport can process messages coming from non-NServiceBus endpoints](https://github.com/Particular/NServiceBus.AmazonSQS/blob/ffe939a71dba32ecd72f1193984ce7940de0709c/src/NServiceBus.Transport.SQS/InputQueuePump.cs#L170-L195).

**Comment by jpalac** [comment]
This has been addressed in [release 6.1.0](https://github.com/Particular/NServiceBus.AmazonSQS/releases/tag/6.1.0)

**Comment by danielmarbach** [comment]
Reopening this issue because the lambda message pump has not been changed and is still making similar assumptions like the old versions of the transport

**Comment by kentdr** [comment]
The Lambda message processing has been changed to match the SQS input queue pump and should resolve this issue.  [See the code in release 1](https://github.com/Particular/NServiceBus.AwsLambda.Sqs/blob/release-1.0/src/NServiceBus.AwsLambda.SQS/AwsLambdaEndpoint.cs#LL270C1-L293C31)
