### ISSUE TITLE
Diagnostics file cannot be written

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.AwsLambda.Sqs#229]
At startup, NServiceBus tries to write the [startup diagnostics file](https://docs.particular.net/nservicebus/hosting/startup-diagnostics), but this file cannot be written on Lambda, so it generates an error message, and there is no recourse available other than to ignore the error every time the Lambda starts up.

**Comment by danielmarbach** [comment]
@DavidBoike it seems [we overwrite the diagnostics writer](https://github.com/Particular/NServiceBus.AwsLambda.Sqs/commit/5af15fd03f9328429f6364ff016b2ffce7a0ef67). This code has been there for a while.

Did you still see the error happening?

// cc @kentdr @timbussmann

**Comment by DavidBoike** [comment]
I don't know, I was working with a customer at the time. But I remember seeing the error message in their environment so something tells me overwriting the diagnostics writer is not working as intended.

**Comment by SzymonPobiega** [comment]
@DavidBoike I tried to repro this with our sample but I've sen no error messages in CloudWatch.

**Comment by DavidBoike** [comment]
If we can't repro it then I would be fine with closing this issue. Who knows what was happening at the time.
