### ISSUE TITLE
Preview package can be used with NServiceBus 8 causing MissingMethodExceptions

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.AwsLambda.Sqs#230]
### Observed behavior

Dependencies for [0.5.0](https://www.nuget.org/packages/NServiceBus.AwsLambda.SQS/0.5.0#dependencies-body-tab) do not use a version range for NServiceBus.AmazonSQS, allowing NServiceBus 8 to be used:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/427110/214946806-041d4604-32ce-4705-bd09-337295d816b2.png">

Execution with NServiceBus 8 causes a MissingMethodException on Endpoint.Start() due to the lack of a `CancellationToken` parameter.

### Expected behavior

A preview locked to NServiceBus 7 should prevent newer NuGet packages from being used.

### Symptoms

MissingMethodException occurs on Lambda exectuion

### Steps to reproduce

Create a Lambda with this package plus fully-updated NuGet packages as much as NuGet will allow with the current versionr anges.

### Is it a regression?

No

### Who's affected

Anyone using this package who also updates NuGet packages :wink:

### Root cause

Binary incompatibility between this package and NServiceBus 8

### Known Workaround

Downgrade packages to NServiceBus.AmazonSQS 5.x and NServiceBus 7.x.

### Triage

Use the following checklist to help triage the bug by assigning the points corresponding to any applicable factors. A staff member from Particular Software will review and adjust if necessary.

| Effect | Points | Notes |
| --- | --- | --- |
| Performance degrades over time requiring manual interventions or automating restarts (1 point) | 0 | |
| The cost of utilizing the Preview significantly exceeds what is justified (2 points) | 0 | |
| The user interface responsiveness is longer than 10s between user request and UI response (1 point) | 1 | |
| The issue impacts the correctness of the system but does not cause irreversible damage (3 points) | 0 | |
| The issue causes unscheduled or unplanned process shutdown. (3 points) | 3 | |
| The issue impacts the system correctness causing irreversible damage (5 points) | | |
| The issue occurs in less than 1 in 1000 usages/invocations (0 points) | 0 | |
| The issue occurs in greater than 1 in 1000 usages/invocations (1 point) | 1 | |
| The issue occurs in greater than 1 in 100 usages/invocations (2 points) | 2 | |
| The issue significantly impacts the adoption of the Preview for the core use-case (3 points) | 3 | |
| Total| 10 |

**Comment by danielmarbach** [comment]
We are currently planning to lock in the dependencies to the SQS transport that targets version 7 of NServiceBus. The PR is available https://github.com/Particular/NServiceBus.AwsLambda.Sqs/issues/230
