### ISSUE TITLE
Document dispatching outside of a message handler + update the sample

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AwsLambda.Sqs#41]
Follow Azure Functions example

**Comment by cquirosj** [comment]
The sample for [Using NServiceBus in AWS Lambda with SQS](https://docs.particular.net/samples/hosting/aws-lambda-sqs/) got [updated](https://github.com/Particular/docs.particular.net/pull/6163) to showcase how to dispatch a message outside of a message handler
