### ISSUE TITLE
State of this Project

### ISSUE THREAD

**Issue by VladimirMakaev** [Particular/NServiceBus.AwsLambda.Sqs#8]
Hi I'm just wondering what is the state of this project / experiment? Is it in working state? 

Are you looking for some feedback or you decided to not implement support for a serverless transport in the future?

I personally find ourselves using NServiceBus less as we tend to build a lot of lambdas these days. But if done right it could be very useful and could reduce the complexity of building message based system where you have lambdas/docker/on-premise components all talking to each other.

**Comment by kbaley** [comment]
@VladimirMakaev AWS Lambda and serverless in general are still very much on our radar and we're working on the best way to support projects in ParticularLabs. Do you have any feedback that you could give on how you would expect to use NServiceBus with AWS Lambda on your projects?

**Comment by VladimirMakaev** [comment]
It looks decent from API surface as I could see in the sample that's why I asked is there is something that is intended to work but doesn't.

Important things I'd personally like to see:
1. It has to be a "zero-cost"-ish in a way on the receiving side. So that if I got an SQSEvent myself deserialized the content to whatever TMessage and invoke on a well known implementation of IHandleMessage<TMessage> manually it wouldn't work any faster then using the NServiceBus pipeline. And features I'm not using should not make my lambda slower.
2. Same is for outgoing if I receive a message, process it and send outgoing message to another endpoint (Lamda on SQS) I couldn't write it any faster than what your outgoing infrastructure is doing.
3. Integration with Subscriptions should work
4. Sagas/Outbox/Persistence
5. Timeouts could theoretically work by queuing up a specific message to self. 
6. Lambda default DLQ is preffered. 
8. Should work with FIFO queues since lambdas support them now.
9. Things that not meant to work should ideally inform us with proper error messages.

**Comment by kbaley** [comment]
@VladimirMakaev Thanks for the detailed feedback, it's appreciated. We'd love to be able to follow up with you in the future when we have firmer plans for the project.

**Comment by tmasternak** [comment]
@VladimirMakaev NServiceBus.AwsLambda.SQS is not available as a public preview. You can find more information in [0.3.1 release notes](https://github.com/Particular/NServiceBus.AwsLambda.Sqs/releases/tag/0.3.1).
